name: Unity Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Setup SSH Keys
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build
      uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: WebGL

    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: build
